Minor edits. Updating configs

diff --git a/board/pure/rootfs-overlay/etc/rc.pure/S95tidal b/board/pure/rootfs-overlay/etc/rc.pure/S95tidal
--- a/board/pure/rootfs-overlay/etc/rc.pure/S95tidal
+++ b/board/pure/rootfs-overlay/etc/rc.pure/S95tidal
@@ -12,8 +12,19 @@ start() {
     sed -i 's/sudo -u root/sudo -u pure/g' /usr/bin/start_tc
     fi
 
+
+
     renice 0 -u dbus
-    start-stop-daemon --start --quiet --background --exec /usr/bin/start_tc 
+#    start-stop-daemon --start --quiet --background --exec /usr/bin/start_tc 
+
+if curl -s http://ipwhois.app/json/ | grep -q  '"country_code":"RU"' ; then
+    start-stop-daemon --start --quiet --background --exec /usr/bin/proxychains4 /usr/bin/start_tc  \
+    && echo "OK" || echo "FAIL"
+else
+    start-stop-daemon --start --quiet --background --exec /usr/bin/start_tc  \
+    && echo "OK" || echo "FAIL"
+fi
+
 
 
 sleep 0.5
